backend:
  name: git-gateway
  branch: main # Vagy 'master', attól függően, mi a fő branch neve a Git repódban

media_folder: "img/uploads" # Ide menti a feltöltött képeket
public_folder: "/img/uploads" # Innen fogja a weboldal betölteni a képeket

collections:
  - name: "gallery" # A kollekció belső neve
    label: "Galéria" # Ez jelenik meg az admin felületen
    files:
      - label: "Munkáink Galéria"
        name: "munkaink"
        file: "data/gallery.json" # Az adatfájl, ahova a képek adatait menti
        fields:
          - label: "Galéria Képek"
            name: "images"
            widget: "list" # Lista, mert több képet is fel lehet tölteni
            fields:
              - { label: "Kép", name: "image", widget: "image" }
              - { label: "Cím", name: "title", widget: "string" }
              - { label: "Leírás", name: "description", widget: "string" }
  - name: "locations"
    label: "Munkaterületek"
    files:
      - label: "Megye Lista"
        name: "counties"
        file: "data/locations.json"
        fields:
          - label: "Megyék"
            name: "counties"
            widget: "list"
            field: { label: "Megye neve", name: "county", widget: "string" }
