backend:
  name: git-gateway
  branch: main  # vagy 'master', ha az a fő ág

media_folder: "img/uploads"     # Ide menti a feltöltött képeket
public_folder: "/img/uploads"   # Ezen az úton éri el a site

collections:
  - name: "gallery"
    label: "Galéria"
    files:
      - label: "Munkáink Galéria"
        name: "munkaink"
        file: "data/gallery.json"
        fields:
          - label: "Galéria Képek"
            name: "images"
            widget: "list"
            fields:
              - { label: "Kép", name: "image", widget: "image" }
              - { label: "Cím", name: "title", widget: "string" }
              - { label: "Leírás", name: "description", widget: "string" }

  - name: "locations"
    label: "Munkaterületek"
    files:
      - label: "Helyszínek"
        name: "locations"
        file: "data/locations.json"
        fields:
          - label: "Megyék"
            name: "counties"
            widget: "list"
            fields:
              - { label: "Megye neve", name: "county_name", widget: "string" }

              - label: "Városok"
                name: "cities"
                widget: "list"
                fields:
                  - { label: "Város neve", name: "city_name", widget: "string" }
                  - { label: "Már dolgoztunk itt?", name: "completed", widget: "boolean", default: false }

