backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "gallery"
    label: "Galéria"
    editor: { preview: false }
    files:
      - label: "Munkáink Galéria"
        name: "munkaink"
        file: "data/gallery.json"
        fields:
          - label: "Galéria Képek"
            name: "images"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "Kép", name: "image", widget: "image" }
              - { label: "Cím", name: "title", widget: "string" }
              - { label: "Leírás", name: "description", widget: "string" }

  - name: "locations"
    label: "Munkaterületek"
    editor: { preview: false }
    files:
      - label: "Helyszínek"
        name: "locations"
        file: "data/locations.json"
        fields:
          - label: "Megyék"
            name: "counties"
            widget: "list"
            collapsed: false
            summary: "{{fields.county_name}} — városok: {{fields.cities.length | default(0)}}"
            fields:
              - { label: "Megye neve", name: "county_name", widget: "string", required: true, hint: "Pl. Somogy, Veszprém, Fejér" }
              - { label: "Megye kijelölve a térképen?", name: "completed", widget: "boolean", default: true }
              - label: "Városok"
                name: "cities"
                widget: "list"
                label_singular: "Város"
                collapsed: true
                summary: "{{fields.city_name | default('— (névtelen)')}}"
                fields:
                  - { label: "Város neve", name: "city_name", widget: "string", required: true, hint: "Pl. Siófok" }
                # NINCS lat/lng mező, a rendszer automatikusan kikeresi
