backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "gallery"
    label: "Galéria"
    editor: { preview: false }
    files:
      - label: "Munkáink Galéria"
        name: "munkaink"
        file: "data/gallery.json"
        fields:
          - label: "Galéria Képek"
            name: "images"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { label: "Kép", name: "image", widget: "image" }
              - { label: "Cím", name: "title", widget: "string" }
              - { label: "Leírás", name: "description", widget: "string" }

  - name: "locations"
    label: "Munkaterületek"
    editor: { preview: false }
    files:
      - label: "Helyszínek"
        name: "locations"
        file: "data/locations.json"
        fields:
          - label: "Megyék"
            name: "counties"
            widget: "list"
            summary: "{{fields.county_name}} — városok: {{fields.cities.length}}"
            fields:
              - { label: "Megye neve", name: "county_name", widget: "string", hint: "Pl. Somogy, Veszprém, Fejér" }
              - label: "Városok"
                name: "cities"
                widget: "list"
                field:
                  label: "Város neve"
                  name: "city"
                  widget: "string"
                  hint: "Pl. Siófok"
