backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"   # alapértelmezett feltöltési hely
public_folder: "/img/uploads"

collections:
  # --- MUNKÁINK GALÉRIA (meglévő) ---
  - name: "gallery"
    label: "Galéria"
    editor: { preview: false }
    files:
      - label: "Munkáink Galéria"
        name: "munkaink"
        file: "data/gallery.json"
        fields:
          - label: "Galéria Képek"
            name: "images"
            widget: "list"
            summary: "{{fields.title | default('Kép')}}"
            fields:
              - { label: "Kép", name: "image", widget: "image", required: true }
              - { label: "Cím (nem kötelező)", name: "title", widget: "string", required: false }
              - { label: "Leírás (nem kötelező)", name: "description", widget: "string", required: false }

  # --- MUNKATERÜLETEK (meglévő) ---
  - name: "locations"
    label: "Munkaterületek"
    editor: { preview: false }
    files:
      - label: "Helyszínek"
        name: "locations"
        file: "data/locations.json"
        fields:
          - label: "Megyék"
            name: "counties"
            widget: "list"
            collapsed: false
            summary: "{{fields.county_name}} — városok: {{fields.cities.length | default(0)}}"
            fields:
              - label: "Megye neve"
                name: "county_name"
                widget: "string"
                required: true
                hint: "Pl. Somogy, Veszprém, Fejér"
              - label: "Megye kijelölve a térképen?"
                name: "completed"
                widget: "boolean"
                default: true
              - label: "Városok"
                name: "cities"
                widget: "list"
                label_singular: "Város"
                collapsed: true
                summary: "{{fields.city_name | default('— (névtelen)')}}"
                fields:
                  - label: "Város neve"
                    name: "city_name"
                    widget: "string"
                    required: true
                    hint: "Pl. Siófok"

  # --- KLÍMA DEKOR GALÉRIA (ÚJ) ---
  - name: "decor"
    label: "Klíma dekor galéria"
    editor: { preview: false }
    # FONTOS: abszolút utak -> mindig a repo gyökeréhez képest
    media_folder: "/img/dekor"
    public_folder: "/img/dekor"
    files:
      - label: "Dekor képek"
        name: "dekor"
        file: "data/dekor.json"
        fields:
          - label: "Képek"
            name: "images"
            widget: "list"
            summary: "Kép"
            fields:
              - { label: "Kép", name: "image", widget: "image", required: true }
              - { label: "Cím (nem kötelező)", name: "title", widget: "string", required: false }
              - { label: "Leírás (nem kötelező)", name: "description", widget: "string", required: false }
